/*
CAR_RENTAL_COMPANY_CAR 테이블과 CAR_RENTAL_COMPANY_RENTAL_HISTORY 테이블과 
CAR_RENTAL_COMPANY_DISCOUNT_PLAN 테이블에서 자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 
2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차에 대해서 
자동차 ID, 자동차 종류, 대여 금액(컬럼명: FEE) 리스트를 출력하는 SQL문을 작성해주세요. 
결과는 대여 금액을 기준으로 내림차순 정렬하고, 대여 금액이 같은 경우 자동차 종류를 기준으로 오름차순 정렬, 자동차 종류까지 같은 경우 자동차 ID를 기준으로 내림차순 정렬해주세요.
자동차 종류가 '세단' 또는 'SUV' 인 자동차 중 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능하고 30일간의 대여 금액이 50만원 이상 200만원 미만인 자동차
-- 코드를 입력하세요
*/
# SELECT 
#     C.CAR_ID, C.CAR_TYPE, ROUND(93/100 * C.DAILY_FEE) AS FEE 
# FROM CAR_RENTAL_COMPANY_CAR C
#     JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
#     JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P ON C.CAR_TYPE = P.CAR_TYPE
# WHERE 
#     (C.CAR_TYPE = '세단' OR 'SUV') AND 
#     BETWEEN('2022-11-01' AND '2022-11-30') AND
#     (500000 <= ROUND(P.DISCOUNT_RATE * C.DAILY_FEE) < 2000000)
# ORDER BY
#     ROUND(0.93 * C.DAILY_FEE) DESC, C.CAR_TYPE ASC, C.CAR_ID DESC;

# SELECT 
#     CRC.CAR_ID, 
#     CRC.CAR_TYPE, 
#     ROUND((CRC.DAILY_FEE * (1 - CRCD.DISCOUNT_RATE / 100)) * 30) AS FEE
#     # CRCH.START_DATE, CRCH.END_DATE
# FROM 
#     CAR_RENTAL_COMPANY_CAR CRC
# LEFT JOIN 
#     CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCH ON CRC.CAR_ID = CRCH.CAR_ID
# LEFT JOIN 
#     CAR_RENTAL_COMPANY_DISCOUNT_PLAN CRCD ON CRC.CAR_TYPE = CRCD.CAR_TYPE
# WHERE 
#     CRC.CAR_TYPE IN ('세단', 'SUV') AND 
#     CRCD.DURATION_TYPE = '30일 이상' AND
#     (END_DATE > '2022-11-01' AND START_DATE < '2022-12-01') AND
#     (CRC.DAILY_FEE * 30) BETWEEN 500000 AND 2000000
# ORDER BY 
#     FEE DESC, CRC.CAR_TYPE, CRC.CAR_ID DESC;

SELECT 
    C.CAR_ID, C.CAR_TYPE, 
    ROUND(C.DAILY_FEE*30*(100-P.DISCOUNT_RATE)/100) AS FEE
FROM 
    CAR_RENTAL_COMPANY_CAR AS C
        JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H ON C.CAR_ID=H.CAR_ID
        JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P ON C.CAR_TYPE=P.CAR_TYPE
WHERE 
    C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
    ) AND P.DURATION_TYPE='30일 이상'
    GROUP BY C.CAR_ID
        HAVING C.CAR_TYPE IN ('세단', 'SUV') AND (FEE>=500000 AND FEE<2000000) 
ORDER BY 
    FEE DESC, CAR_TYPE, CAR_ID DESC
