/*
KL_PLAYER 테이블은 K-리그에 소속된 모든 프로 축구 선수들에 대한 정보를 담은 테이블입니다.
이 테이블의 구조는 아래와 같으며, PLAYER_ID, PLAYER_NAME, E_PLAYER_NAME, NICKNAME, JOIN_YYYY, POSITION, BACK_NO, NATION, BIRTH_DATE, HEIGHT, WEIGHT, TEAM_ID는 각각 선수의 아이디, 이름, 영문 이름, 별명, 입단년도, 포지션, 백넘버, 출신국, 생일, 키, 몸무게 그리고 소속팀 아이디를 나타냅니다.

NAME	TYPE	NULLABLE
PLAYER_ID	VARCHAR(N)	FALSE
PLAYER_NAME	VARCHAR(N)	FALSE
E_PLAYER_NAME	VARCHAR(N)	TRUE
NICKNAME	VARCHAR(N)	TRUE
JOIN_YYYY	VARCHAR(N)	TRUE
POSITION	VARCHAR(N)	TRUE
BACK_NO	INTEGER	TRUE
NATION	VARCHAR(N)	TRUE
BIRTH_DATE	DATE	TRUE
HEIGHT	INTEGER	TRUE
WEIGHT	INTEGER	TRUE
TEAM_ID	VARCHAR(N)	FALSE
KL_TEAM 테이블은 K-리그에 참여하는 모든 프로 축구 팀들에 대한 정보를 담은 테이블입니다.
이 테이블의 구조는 아래와 같으며, TEAM_ID, TEAM_NAME, E_TEAM_NAME, REGION_NAME, ORIG_YYYY, ADDRESS, TEL, STADIUM_ID는 각각 팀의 아이디, 이름, 영문 이름, 연고지, 창단년도, 주소, 전화번호 그리고 전용경기장 아이디를 나타냅니다.

NAME	TYPE	NULLABLE
TEAM_ID	VARCHAR(N)	FALSE
TEAM_NAME	VARCHAR(N)	FALSE
E_TEAM_NAME	VARCHAR(N)	TRUE
REGION_NAME	VARCHAR(N)	FALSE
ORIG_YYYY	VARCHAR(N)	TRUE
ADDRESS	VARCHAR(N)	TRUE
TEL	VARCHAR(N)	TRUE
STADIUM_ID	VARCHAR(N)	FALSE
각 팀에서 키가 제일 작은 선수를 검색하는 SQL문을 작성하세요.
키가 제일 작은 선수가 여럿 있을 때는 모두 출력합니다.
출력 컬럼은 TEAM_NAME, PLAYER_NAME, POSITION, HEIGHT 순으로 합니다.
이때 결과는 HEIGHT, TEAM_NAME, PLAYER_NAME의 오름차순으로 정렬합니다.
*/

SELECT KT.TEAM_NAME, KP.PLAYER_NAME, KP.POSITION, KP.HEIGHT
FROM KL_PLAYER KP
JOIN KL_TEAM KT ON KP.TEAM_ID = KT.TEAM_ID
WHERE (KT.TEAM_ID, KP.HEIGHT) IN (
        SELECT TEAM_ID, MIN(HEIGHT)
        FROM KL_PLAYER
        GROUP BY TEAM_ID
      )
ORDER BY KP.HEIGHT ASC, KT.TEAM_NAME ASC, KP.PLAYER_NAME ASC;
